-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 17:08:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema error404
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema error404
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `error404` DEFAULT CHARACTER SET utf8 ;
USE `error404` ;

-- -----------------------------------------------------
-- Table `error404`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(255) NOT NULL,
  `age` INT NULL,
  `roles_id` INT NOT NULL,
  `promo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`, `promo_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ) ,
  INDEX `fk_user_roles_idx` (`roles_id` ) ,
  INDEX `fk_user_promo1_idx` (`promo_id` ) ,
  CONSTRAINT `fk_user_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `error404`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `error404`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `dateStart` DATE NOT NULL,
  `place` LONGTEXT NOT NULL,
  `dateEnd` DATE NOT NULL,
  `registerDateEnd` DATE NOT NULL,
  `image` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`user_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`user_has_event` (
  `user_id` INT NOT NULL,
  `user_roles_id` INT NOT NULL,
  `user_promo_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_roles_id`, `user_promo_id`, `event_id`),
  INDEX `fk_user_has_event_event1_idx` (`event_id` ) ,
  INDEX `fk_user_has_event_user1_idx` (`user_id` , `user_roles_id` , `user_promo_id` ) ,
  CONSTRAINT `fk_user_has_event_user1`
    FOREIGN KEY (`user_id` , `user_roles_id` , `user_promo_id`)
    REFERENCES `error404`.`user` (`id` , `roles_id` , `promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `error404`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saleDate` DATE NOT NULL,
  `file` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `user_roles_id` INT NOT NULL,
  `user_promo_id` INT NOT NULL,
  `number` INT NULL,
  `price` FLOAT NOT NULL,
  `receiver` LONGTEXT NOT NULL,
  `sender` LONGTEXT NOT NULL,
  `details` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `user_roles_id`, `user_promo_id`),
  INDEX `fk_invoice_user1_idx` (`user_id` , `user_roles_id` , `user_promo_id` ) ,
  CONSTRAINT `fk_invoice_user1`
    FOREIGN KEY (`user_id` , `user_roles_id` , `user_promo_id`)
    REFERENCES `error404`.`user` (`id` , `roles_id` , `promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `error404`.`quote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `error404`.`quote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saleDate` DATE NOT NULL,
  `file` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `user_roles_id` INT NOT NULL,
  `user_promo_id` INT NOT NULL,
  `number` INT NULL,
  `price` FLOAT NOT NULL,
  `receiver` LONGTEXT NOT NULL,
  `sender` LONGTEXT NOT NULL,
  `details` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `user_roles_id`, `user_promo_id`),
  INDEX `fk_invoice_user1_idx` (`user_id` , `user_roles_id` , `user_promo_id` ) ,
  CONSTRAINT `fk_invoice_user10`
    FOREIGN KEY (`user_id` , `user_roles_id` , `user_promo_id`)
    REFERENCES `error404`.`user` (`id` , `roles_id` , `promo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 